/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Batch {
  'id' : BatchId,
  'purchasePrice' : number,
  'expiryDate' : Timestamp,
  'createdAt' : Timestamp,
  'manufacturedDate' : [] | [Timestamp],
  'batchNumber' : string,
  'quantity' : bigint,
  'drugId' : DrugId,
}
export type BatchId = bigint;
export interface BatchInput {
  'purchasePrice' : number,
  'expiryDate' : Timestamp,
  'manufacturedDate' : [] | [Timestamp],
  'batchNumber' : string,
  'quantity' : bigint,
  'drugId' : DrugId,
}
export interface Bill {
  'id' : BillId,
  'note' : string,
  'extractedText' : [] | [string],
  'filename' : string,
  'image' : ExternalBlob,
  'uploadedAt' : Timestamp,
}
export type BillId = bigint;
export interface BillInput {
  'note' : string,
  'filename' : string,
  'image' : ExternalBlob,
}
export interface DashboardStats {
  'lowStockBatchCount' : bigint,
  'totalBatches' : bigint,
  'totalDrugs' : bigint,
  'expiringSoonCount' : bigint,
}
export interface DispenseInput { 'quantity' : bigint, 'batchId' : BatchId }
export interface Drug {
  'id' : DrugId,
  'manufacturer' : string,
  'name' : string,
  'createdAt' : Timestamp,
  'description' : string,
  'updatedAt' : Timestamp,
  'salePrice' : number,
}
export type DrugId = bigint;
export interface DrugInput {
  'manufacturer' : string,
  'name' : string,
  'description' : string,
  'salePrice' : number,
}
export interface DrugWithBatches { 'drug' : Drug, 'batches' : Array<Batch> }
export interface ExpiryAlert {
  'drugName' : string,
  'expiryDate' : Timestamp,
  'batchNumber' : string,
  'quantity' : bigint,
  'batchId' : BatchId,
  'dismissed' : boolean,
  'drugId' : DrugId,
}
export type ExternalBlob = Uint8Array;
export type Timestamp = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'addBatch' : ActorMethod<[BatchInput], Batch>,
  'addDrug' : ActorMethod<[DrugInput], Drug>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteBatch' : ActorMethod<[BatchId], undefined>,
  'deleteBill' : ActorMethod<[BillId], undefined>,
  'deleteDrug' : ActorMethod<[DrugId], undefined>,
  'dismissAlert' : ActorMethod<[BatchId], undefined>,
  'dispenseDrug' : ActorMethod<[DispenseInput], undefined>,
  'extractBillText' : ActorMethod<[BillId], string>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDashboardStats' : ActorMethod<[], DashboardStats>,
  'getDrug' : ActorMethod<[DrugId], [] | [DrugWithBatches]>,
  'getExpiryAlerts' : ActorMethod<[bigint], Array<ExpiryAlert>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listBills' : ActorMethod<[], Array<Bill>>,
  'listDrugs' : ActorMethod<[[] | [string]], Array<DrugWithBatches>>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateBatch' : ActorMethod<[BatchId, BatchInput], Batch>,
  'updateDrug' : ActorMethod<[DrugId, DrugInput], Drug>,
  'uploadBill' : ActorMethod<[BillInput], Bill>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];