/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Timestamp = IDL.Int;
export const DrugId = IDL.Nat;
export const BatchInput = IDL.Record({
  'purchasePrice' : IDL.Float64,
  'expiryDate' : Timestamp,
  'manufacturedDate' : IDL.Opt(Timestamp),
  'batchNumber' : IDL.Text,
  'quantity' : IDL.Nat,
  'drugId' : DrugId,
});
export const BatchId = IDL.Nat;
export const Batch = IDL.Record({
  'id' : BatchId,
  'purchasePrice' : IDL.Float64,
  'expiryDate' : Timestamp,
  'createdAt' : Timestamp,
  'manufacturedDate' : IDL.Opt(Timestamp),
  'batchNumber' : IDL.Text,
  'quantity' : IDL.Nat,
  'drugId' : DrugId,
});
export const DrugInput = IDL.Record({
  'manufacturer' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'salePrice' : IDL.Float64,
});
export const Drug = IDL.Record({
  'id' : DrugId,
  'manufacturer' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'description' : IDL.Text,
  'updatedAt' : Timestamp,
  'salePrice' : IDL.Float64,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const BillId = IDL.Nat;
export const DispenseInput = IDL.Record({
  'quantity' : IDL.Nat,
  'batchId' : BatchId,
});
export const DashboardStats = IDL.Record({
  'lowStockBatchCount' : IDL.Nat,
  'totalBatches' : IDL.Nat,
  'totalDrugs' : IDL.Nat,
  'expiringSoonCount' : IDL.Nat,
});
export const DrugWithBatches = IDL.Record({
  'drug' : Drug,
  'batches' : IDL.Vec(Batch),
});
export const ExpiryAlert = IDL.Record({
  'drugName' : IDL.Text,
  'expiryDate' : Timestamp,
  'batchNumber' : IDL.Text,
  'quantity' : IDL.Nat,
  'batchId' : BatchId,
  'dismissed' : IDL.Bool,
  'drugId' : DrugId,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Bill = IDL.Record({
  'id' : BillId,
  'note' : IDL.Text,
  'extractedText' : IDL.Opt(IDL.Text),
  'filename' : IDL.Text,
  'image' : ExternalBlob,
  'uploadedAt' : Timestamp,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const BillInput = IDL.Record({
  'note' : IDL.Text,
  'filename' : IDL.Text,
  'image' : ExternalBlob,
});

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControl' : IDL.Func([], [], []),
  'addBatch' : IDL.Func([BatchInput], [Batch], []),
  'addDrug' : IDL.Func([DrugInput], [Drug], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteBatch' : IDL.Func([BatchId], [], []),
  'deleteBill' : IDL.Func([BillId], [], []),
  'deleteDrug' : IDL.Func([DrugId], [], []),
  'dismissAlert' : IDL.Func([BatchId], [], []),
  'dispenseDrug' : IDL.Func([DispenseInput], [], []),
  'extractBillText' : IDL.Func([BillId], [IDL.Text], []),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
  'getDrug' : IDL.Func([DrugId], [IDL.Opt(DrugWithBatches)], ['query']),
  'getExpiryAlerts' : IDL.Func([IDL.Nat], [IDL.Vec(ExpiryAlert)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listBills' : IDL.Func([], [IDL.Vec(Bill)], ['query']),
  'listDrugs' : IDL.Func(
      [IDL.Opt(IDL.Text)],
      [IDL.Vec(DrugWithBatches)],
      ['query'],
    ),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateBatch' : IDL.Func([BatchId, BatchInput], [Batch], []),
  'updateDrug' : IDL.Func([DrugId, DrugInput], [Drug], []),
  'uploadBill' : IDL.Func([BillInput], [Bill], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Timestamp = IDL.Int;
  const DrugId = IDL.Nat;
  const BatchInput = IDL.Record({
    'purchasePrice' : IDL.Float64,
    'expiryDate' : Timestamp,
    'manufacturedDate' : IDL.Opt(Timestamp),
    'batchNumber' : IDL.Text,
    'quantity' : IDL.Nat,
    'drugId' : DrugId,
  });
  const BatchId = IDL.Nat;
  const Batch = IDL.Record({
    'id' : BatchId,
    'purchasePrice' : IDL.Float64,
    'expiryDate' : Timestamp,
    'createdAt' : Timestamp,
    'manufacturedDate' : IDL.Opt(Timestamp),
    'batchNumber' : IDL.Text,
    'quantity' : IDL.Nat,
    'drugId' : DrugId,
  });
  const DrugInput = IDL.Record({
    'manufacturer' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'salePrice' : IDL.Float64,
  });
  const Drug = IDL.Record({
    'id' : DrugId,
    'manufacturer' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'description' : IDL.Text,
    'updatedAt' : Timestamp,
    'salePrice' : IDL.Float64,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const BillId = IDL.Nat;
  const DispenseInput = IDL.Record({
    'quantity' : IDL.Nat,
    'batchId' : BatchId,
  });
  const DashboardStats = IDL.Record({
    'lowStockBatchCount' : IDL.Nat,
    'totalBatches' : IDL.Nat,
    'totalDrugs' : IDL.Nat,
    'expiringSoonCount' : IDL.Nat,
  });
  const DrugWithBatches = IDL.Record({
    'drug' : Drug,
    'batches' : IDL.Vec(Batch),
  });
  const ExpiryAlert = IDL.Record({
    'drugName' : IDL.Text,
    'expiryDate' : Timestamp,
    'batchNumber' : IDL.Text,
    'quantity' : IDL.Nat,
    'batchId' : BatchId,
    'dismissed' : IDL.Bool,
    'drugId' : DrugId,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Bill = IDL.Record({
    'id' : BillId,
    'note' : IDL.Text,
    'extractedText' : IDL.Opt(IDL.Text),
    'filename' : IDL.Text,
    'image' : ExternalBlob,
    'uploadedAt' : Timestamp,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const BillInput = IDL.Record({
    'note' : IDL.Text,
    'filename' : IDL.Text,
    'image' : ExternalBlob,
  });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControl' : IDL.Func([], [], []),
    'addBatch' : IDL.Func([BatchInput], [Batch], []),
    'addDrug' : IDL.Func([DrugInput], [Drug], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteBatch' : IDL.Func([BatchId], [], []),
    'deleteBill' : IDL.Func([BillId], [], []),
    'deleteDrug' : IDL.Func([DrugId], [], []),
    'dismissAlert' : IDL.Func([BatchId], [], []),
    'dispenseDrug' : IDL.Func([DispenseInput], [], []),
    'extractBillText' : IDL.Func([BillId], [IDL.Text], []),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
    'getDrug' : IDL.Func([DrugId], [IDL.Opt(DrugWithBatches)], ['query']),
    'getExpiryAlerts' : IDL.Func([IDL.Nat], [IDL.Vec(ExpiryAlert)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listBills' : IDL.Func([], [IDL.Vec(Bill)], ['query']),
    'listDrugs' : IDL.Func(
        [IDL.Opt(IDL.Text)],
        [IDL.Vec(DrugWithBatches)],
        ['query'],
      ),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateBatch' : IDL.Func([BatchId, BatchInput], [Batch], []),
    'updateDrug' : IDL.Func([DrugId, DrugInput], [Drug], []),
    'uploadBill' : IDL.Func([BillInput], [Bill], []),
  });
};

export const init = ({ IDL }) => { return []; };